-- Public booking page (/booking/<token>).
--
-- 1. bookings.public_token: short URL-safe token identifying a booking on the
--    public booking-details page. Generated by default for new bookings; synced
--    bookings keep the token Xano already emailed (bookingConfirmation_id),
--    carried over by the xano-booking-sync function.
-- 2. businesses.contact_email: the support email shown to guests.
--
-- No anon RLS policy is added: the public page reads server-side with the
-- service role (same pattern as /gp) and only ever by exact token.

create or replace function public.generate_booking_token()
returns text
language sql
volatile
set search_path = ''
as $$
  select string_agg(
    substr(
      'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789',
      (get_byte(extensions.gen_random_bytes(1), 0) % 55) + 1,
      1
    ),
    ''
  )
  from generate_series(1, 10);
$$;

comment on function public.generate_booking_token() is
  'Random 10-char token for the public booking page. Xano-synced bookings use the 9-char token Xano emailed instead, so lengths never collide.';

-- Volatile default: Postgres rewrites the table and evaluates the default per
-- row, so every existing booking gets its own token in this one statement.
alter table public.bookings
  add column public_token text not null default public.generate_booking_token();

create unique index bookings_public_token_key on public.bookings (public_token);

alter table public.businesses
  add column contact_email text;
